name: Linting and formatting on PR
on:
  push
  

jobs:
  super-lint:
    name: Lint code base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Install Dependencies
        run: npm install

      - name: Run linting check
        run: npm run lint:check

      - name: Check formatting
        run: npm run format:check

      - name: builds check
        run: npm run build

      - name: Run Super-Linter
        uses: github/super-linter@v4
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
